### ISSUE TITLE
Filtros ranking fora do padrão

### ISSUE THREAD

**Issue by franciscoasantos** [OsivaTech/palpitefc-front-new#10]
### Component
Ranking

### Description
Os filtros da tela ranking estão fora do padrão de espaçamento (padding/margin), se comparamos com os filtros de partida.
![image](https://github.com/OsivaTech/palpitefc-front-new/assets/47906321/3c394782-a628-4418-bfcd-58bafbb5c53b)
![image](https://github.com/OsivaTech/palpitefc-front-new/assets/47906321/be8be55a-84b1-44f6-af0e-8957f4b0d936)

**Comment by Guilbritto** [comment]
https://github.com/OsivaTech/palpitefc-front-new/assets/6548060/a7bec11b-c528-4262-9e69-dee51f3a807f
