### ISSUE TITLE
Existem duas rolagens na página

### ISSUE THREAD

**Issue by franciscoasantos** [OsivaTech/palpitefc-front-new#11]
### Compnonent
Home page

### Description
Existem duas rolagens na página, uma delas ocasiona o desaparecimento do banner, que deveria ser fixo. Isso também ocorre quando tentamos rolar no final da página

https://github.com/OsivaTech/palpitefc-front-new/assets/47906321/6c796a72-ab01-42ee-8413-cd7d95d298b0

https://github.com/OsivaTech/palpitefc-front-new/assets/47906321/119cb719-e8f4-445c-9ddc-ee12dcd8c344

**Comment by Guilbritto** [comment]
https://github.com/OsivaTech/palpitefc-front-new/assets/6548060/b9f88c8f-de58-49f9-a936-30afcda3e6b7
