### ISSUE TITLE
[FEATURE] - Rolagem automática do banner

### ISSUE THREAD

**Issue by franciscoasantos** [OsivaTech/palpitefc-front-new#2]
Criar rolagem automática das imagens do banner. O tempo de rolagem de cada imagem, deve seguir o tempo estipulado no contrato de resposta do endpoint GET > /advetisement (campo showTime)
  {
    "id": 1,
    "name": "Banner 1",
    "description": "Palpite Futebol Clube - Em breve",
    "imageBanner": "https://palpitefutebolclube.com/images/banner.png",
    "delay": 5000, //milissegundos
    "imageCard": "https://palpitefutebolclube.com/images/banner.png",
    "enabled": true,
    "startDate": "2024-06-24T18:23:08.194Z",
    "endDate": "2025-06-24T18:23:08.194Z",
    "urlGoTo": "https://palpitefutebolclube.com/"
  }

**Comment by Guilbritto** [comment]
https://github.com/OsivaTech/palpitefc-front-new/assets/6548060/8e591d67-ef56-4285-9dc9-4507cd1e1ba7
