### ISSUE TITLE
Loading nas ações do site

### ISSUE THREAD

**Issue by franciscoasantos** [OsivaTech/palpitefc-front-new#6]
### Description
Precisamos adicionar um loading nas ações mais demoradas do site, ex. login, cadastro, etc. Para que o usuário tenha um feedback de que algo está acontecendo.

**Comment by Guilbritto** [comment]
### Login


https://github.com/OsivaTech/palpitefc-front-new/assets/6548060/79b7e8dc-01c3-45c4-9fa5-e479274a6f5d

**Comment by Guilbritto** [comment]
### Register


https://github.com/OsivaTech/palpitefc-front-new/assets/6548060/3d38a8c6-1509-4c23-af12-be1016ee1502
