### ISSUE TITLE
Erros ao lançar palpite não é mostrado

### ISSUE THREAD

**Issue by franciscoasantos** [OsivaTech/palpitefc-front-new#8]
### Component
Guess Card

### Description
Ao realizar um palpite de um jogo que já iniciou, nenhum erro é mostrado na tela.

https://github.com/OsivaTech/palpitefc-front-new/assets/47906321/739f8523-6b36-435e-8091-9bd3fa2bc11a

**Comment by Guilbritto** [comment]
https://github.com/OsivaTech/palpitefc-front-new/assets/6548060/f0ad97ff-8887-4315-bd4d-fced01ff0912
